[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Xmx2G -Xms2G -jar fabric-server-launcher.jar nogui"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[ports]]
port = "25565"
protocol = "tcp"
